name: MultimerMapper
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.14
  - biopython==1.82
  - pandas==1.5.3
  - numpy==1.25.0
  - matplotlib==3.8.0
  - python-igraph=0.11.3
  - plotly==5.18.0
  - ipython==8.20.0
  - pycairo==1.26.1
  - cairocffi==1.6.1
  - scikit-learn==1.3.0
